In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
df=pd.read_csv("../datasets/SS_meridian.csv")

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C

In [7]:
df.map(lambda cell: str(cell)+"--")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1--,0--,3--,"Clark, Miss Mabel--",female--,22.9--,2--,1--,SM70415--,3.5--,nan--,M--
1,2--,1--,3--,"Lewis, Miss Margaret--",female--,59.8--,1--,0--,SM69589--,4.35--,nan--,L--
2,3--,1--,2--,"Garcia, Mrs. Anna--",female--,nan--,1--,0--,SM43901--,14.88--,nan--,C--
3,4--,0--,2--,"Parker, Mrs. Violet--",female--,27.7--,0--,1--,SM68491--,26.51--,nan--,L--
4,5--,1--,1--,"Adams, Miss Rose--",female--,52.1--,1--,1--,SM16863--,65.47--,nan--,C--
...,...,...,...,...,...,...,...,...,...,...,...,...
686,687--,1--,1--,"Jackson, Lady Florence--",female--,34.6--,0--,0--,SM85340--,100.78--,B72--,C--
687,688--,0--,2--,"Walker, Mr. Robert--",male--,34.6--,2--,0--,SM95119--,25.18--,nan--,M--
688,689--,1--,1--,"Jackson, Lady Violet--",female--,45.7--,0--,0--,SM87624--,48.47--,nan--,L--
689,690--,1--,1--,"Harris, Mrs. Gladys--",female--,43.2--,0--,0--,SM59207--,42.19--,D20--,M--
690,691--,0--,3--,"Green, Mrs. Clara--",female--,33.1--,0--,0--,SM30204--,5.21--,nan--,M--

In [8]:
def display_item(item):
    print(item)
    print()

In [10]:
df.apply(display_item)

0        1
1        2
2        3
3        4
4        5
      ...
686    687
687    688
688    689
689    690
690    691
Name: PassengerId, Length: 691, dtype: int64

0      0
1      1
2      1
3      0
4      1
      ..
686    1
687    0
688    1
689    1
690    0
Name: Survived, Length: 691, dtype: int64

0      3
1      3
2      2
3      2
4      1
      ..
686    1
687    2
688    1
689    1
690    3
Name: Pclass, Length: 691, dtype: int64

0           Clark, Miss Mabel
1        Lewis, Miss Margaret
2           Garcia, Mrs. Anna
3         Parker, Mrs. Violet
4            Adams, Miss Rose
                ...
686    Jackson, Lady Florence
687        Walker, Mr. Robert
688      Jackson, Lady Violet
689       Harris, Mrs. Gladys
690         Green, Mrs. Clara
Name: Name, Length: 691, dtype: object

0      female
1      female
2      female
3      female
4      female
        ...
686    female
687      male
688    female
689    female
690    female
Name: Sex, Length: 691, dtype: object

0      22.9
1      59.8
2       NaN
3      27.7
4      52.1
       ...
686    34.6
687    34.6
688    45.7
689    43.2
690    33.1
Name: Age, Length: 691, dtype: float64

0      2
1      1
2      1
3      0
4      1
      ..
686    0
687    2
688    0
689    0
690    0
Name: SibSp, Length: 691, dtype: int64

0      1
1      0
2      0
3      1
4      1
      ..
686    0
687    0
688    0
689    0
690    0
Name: Parch, Length: 691, dtype: int64

0      SM70415
1      SM69589
2      SM43901
3      SM68491
4      SM16863
        ...
686    SM85340
687    SM95119
688    SM87624
689    SM59207
690    SM30204
Name: Ticket, Length: 691, dtype: object

0        3.50
1        4.35
2       14.88
3       26.51
4       65.47
        ...
686    100.78
687     25.18
688     48.47
689     42.19
690      5.21
Name: Fare, Length: 691, dtype: float64

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
686    B72
687    NaN
688    NaN
689    D20
690    NaN
Name: Cabin, Length: 691, dtype: object

0      M
1      L
2      C
3      L
4      C
      ..
686    C
687    M
688    L
689    M
690    M
Name: Embarked, Length: 691, dtype: object

PassengerId    None
Survived       None
Pclass         None
Name           None
Sex            None
Age            None
SibSp          None
Parch          None
Ticket         None
Fare           None
Cabin          None
Embarked       None
dtype: object

In [11]:
df.apply(display_item,axis=1)

PassengerId                    1
Survived                       0
Pclass                         3
Name           Clark, Miss Mabel
Sex                       female
Age                         22.9
SibSp                          2
Parch                          1
Ticket                   SM70415
Fare                         3.5
Cabin                        NaN
Embarked                       M
Name: 0, dtype: object

PassengerId                       2
Survived                          1
Pclass                            3
Name           Lewis, Miss Margaret
Sex                          female
Age                            59.8
SibSp                             1
Parch                             0
Ticket                      SM69589
Fare                           4.35
Cabin                           NaN
Embarked                          L
Name: 1, dtype: object

PassengerId                    3
Survived                       1
Pclass                         2
Name           Garcia, Mrs. Anna
Sex                       female
Age                          NaN
SibSp                          1
Parch                          0
Ticket                   SM43901
Fare                       14.88
Cabin                        NaN
Embarked                       C
Name: 2, dtype: object

PassengerId                      4
Survived                         0
Pclass                           2
Name           Parker, Mrs. Violet
Sex                         female
Age                           27.7
SibSp                            0
Parch                            1
Ticket                     SM68491
Fare                         26.51
Cabin                          NaN
Embarked                         L
Name: 3, dtype: object

PassengerId                   5
Survived                      1
Pclass                        1
Name           Adams, Miss Rose
Sex                      female
Age                        52.1
SibSp                         1
Parch                         1
Ticket                  SM16863
Fare                      65.47
Cabin                       NaN
Embarked                      C
Name: 4, dtype: object

PassengerId                     6
Survived                        1
Pclass                          3
Name           Harris, Miss Grace
Sex                        female
Age                          30.9
SibSp                           0
Parch                           2
Ticket                    SM34535
Fare                          3.5
Cabin                         NaN
Embarked                        L
Name: 5, dtype: object

PassengerId                      7
Survived                         0
Pclass                           1
Name           Stewart, Mr. Ernest
Sex                           male
Age                           57.9
SibSp                            0
Parch                            0
Ticket                     SM66985
Fare                         72.69
Cabin                          A43
Embarked                         M
Name: 6, dtype: object

PassengerId                      8
Survived                         1
Pclass                           2
Name           Jones, Mr. Clarence
Sex                           male
Age                            8.4
SibSp                            1
Parch                            1
Ticket                     SM37886
Fare                          7.95
Cabin                          NaN
Embarked                         C
Name: 7, dtype: object

PassengerId                       9
Survived                          0
Pclass                            3
Name           Allen, Mr. Frederick
Sex                            male
Age                             0.5
SibSp                             0
Parch                             0
Ticket                      SM87459
Fare                            4.8
Cabin                           NaN
Embarked                          L
Name: 8, dtype: object

PassengerId                          10
Survived                              0
Pclass                                1
Name           Sanchez, Countess Violet
Sex                              female
Age                                45.2
SibSp                                 1
Parch                                 1
Ticket                          SM58085
Fare                              97.86
Cabin                               A66
Embarked                              C
Name: 9, dtype: object

PassengerId                    11
Survived                        0
Pclass                          3
Name           Lopez, Mr. Raymond
Sex                          male
Age                          16.1
SibSp                           0
Parch                           0
Ticket                    SM42189
Fare                         5.58
Cabin                         NaN
Embarked                        M
Name: 10, dtype: object

PassengerId                        12
Survived                            1
Pclass                              1
Name           Jackson, Lady Gertrude
Sex                            female
Age                              37.7
SibSp                               0
Parch                               1
Ticket                        SM20561
Fare                            56.52
Cabin                             B59
Embarked                            C
Name: 11, dtype: object

PassengerId                     13
Survived                         1
Pclass                           1
Name           Sanchez, Lady Agnes
Sex                         female
Age                           28.3
SibSp                            0
Parch                            0
Ticket                     SM80776
Fare                         91.66
Cabin                          A86
Embarked                         L
Name: 12, dtype: object

PassengerId                       14
Survived                           1
Pclass                             3
Name           Nelson, Mr. Frederick
Sex                             male
Age                             37.4
SibSp                              0
Parch                              0
Ticket                       SM86865
Fare                            7.65
Cabin                            NaN
Embarked                           C
Name: 13, dtype: object

PassengerId                       15
Survived                           1
Pclass                             2
Name           Phillips, Miss Louisa
Sex                           female
Age                             12.7
SibSp                              1
Parch                              0
Ticket                       SM12587
Fare                           23.65
Cabin                            E46
Embarked                           L
Name: 14, dtype: object

PassengerId                     16
Survived                         1
Pclass                           3
Name           King, Mrs. Florence
Sex                         female
Age                           12.6
SibSp                            1
Parch                            1
Ticket                     SM59664
Fare                         11.01
Cabin                          NaN
Embarked                         L
Name: 15, dtype: object

PassengerId                  17
Survived                      0
Pclass                        3
Name           Perez, Mrs. Rose
Sex                      female
Age                        29.0
SibSp                         0
Parch                         0
Ticket                  SM22648
Fare                       7.35
Cabin                       NaN
Embarked                      M
Name: 16, dtype: object

PassengerId                    18
Survived                        1
Pclass                          3
Name           Adams, Mr. William
Sex                          male
Age                           NaN
SibSp                           3
Parch                           0
Ticket                    SM99505
Fare                         3.56
Cabin                         NaN
Embarked                        M
Name: 17, dtype: object

PassengerId                      19
Survived                          1
Pclass                            1
Name           Thompson, Mrs. Helen
Sex                          female
Age                            34.9
SibSp                             0
Parch                             0
Ticket                      SM86271
Fare                          74.69
Cabin                           NaN
Embarked                          L
Name: 18, dtype: object

PassengerId                  20
Survived                      1
Pclass                        2
Name           Lee, Miss Gladys
Sex                      female
Age                        42.1
SibSp                         0
Parch                         0
Ticket                  SM28350
Fare                      28.63
Cabin                       NaN
Embarked                      L
Name: 19, dtype: object

PassengerId                   21
Survived                       0
Pclass                         3
Name           Clark, Mr. Samuel
Sex                         male
Age                         26.7
SibSp                          0
Parch                          0
Ticket                   SM51229
Fare                       11.39
Cabin                        NaN
Embarked                       M
Name: 20, dtype: object

PassengerId                     22
Survived                         0
Pclass                           1
Name           Edwards, Mr. Alfred
Sex                           male
Age                           58.6
SibSp                            1
Parch                            0
Ticket                     SM77889
Fare                         20.99
Cabin                          B25
Embarked                         C
Name: 21, dtype: object

PassengerId                     23
Survived                         0
Pclass                           3
Name           Harris, Mr. Michael
Sex                           male
Age                            0.5
SibSp                            0
Parch                            0
Ticket                     SM66372
Fare                          8.05
Cabin                          NaN
Embarked                         L
Name: 22, dtype: object

PassengerId                    24
Survived                        0
Pclass                          3
Name           Carter, Mr. Albert
Sex                          male
Age                          27.1
SibSp                           0
Parch                           0
Ticket                    SM54767
Fare                        13.89
Cabin                         NaN
Embarked                        L
Name: 23, dtype: object

PassengerId                     25
Survived                         1
Pclass                           1
Name           Lewis, Lady Harriet
Sex                         female
Age                           71.1
SibSp                            0
Parch                            0
Ticket                     SM39603
Fare                        133.21
Cabin                          A93
Embarked                         M
Name: 24, dtype: object

PassengerId                      26
Survived                          1
Pclass                            3
Name           Clark, Mrs. Winifred
Sex                          female
Age                            16.5
SibSp                             2
Parch                             2
Ticket                      SM24984
Fare                            3.5
Cabin                           NaN
Embarked                          C
Name: 25, dtype: object

PassengerId                    27
Survived                        0
Pclass                          3
Name           Sanchez, Mr. Frank
Sex                          male
Age                          16.5
SibSp                           3
Parch                           0
Ticket                    SM97135
Fare                        10.36
Cabin                         NaN
Embarked                        C
Name: 26, dtype: object

PassengerId                   28
Survived                       0
Pclass                         3
Name           Martin, Mr. Frank
Sex                         male
Age                         36.2
SibSp                          1
Parch                          0
Ticket                   SM53452
Fare                        9.05
Cabin                        NaN
Embarked                       M
Name: 27, dtype: object

PassengerId                   29
Survived                       1
Pclass                         2
Name           Walker, Mrs. Mary
Sex                       female
Age                         25.8
SibSp                          1
Parch                          0
Ticket                   SM19514
Fare                        20.4
Cabin                        NaN
Embarked                       C
Name: 28, dtype: object

PassengerId                       30
Survived                           1
Pclass                             2
Name           Martinez, Mr. Michael
Sex                             male
Age                             38.4
SibSp                              1
Parch                              0
Ticket                       SM84572
Fare                           27.79
Cabin                            NaN
Embarked                           L
Name: 29, dtype: object

PassengerId                        31
Survived                            0
Pclass                              3
Name           Anderson, Mr. Clarence
Sex                              male
Age                              18.6
SibSp                               0
Parch                               0
Ticket                        SM37147
Fare                              5.6
Cabin                             NaN
Embarked                            M
Name: 30, dtype: object

PassengerId                      32
Survived                          0
Pclass                            3
Name           Evans, Mrs. Beatrice
Sex                          female
Age                            48.5
SibSp                             0
Parch                             0
Ticket                      SM70314
Fare                          13.82
Cabin                           NaN
Embarked                          C
Name: 31, dtype: object

PassengerId                  33
Survived                      1
Pclass                        1
Name           Walker, Miss Ida
Sex                      female
Age                        30.2
SibSp                         0
Parch                         0
Ticket                  SM24790
Fare                     144.37
Cabin                       D88
Embarked                      M
Name: 32, dtype: object

PassengerId                      34
Survived                          1
Pclass                            3
Name           Stewart, Mrs. Gladys
Sex                          female
Age                            46.2
SibSp                             2
Parch                             1
Ticket                      SM35106
Fare                          11.08
Cabin                           NaN
Embarked                          M
Name: 33, dtype: object

PassengerId                   35
Survived                       0
Pclass                         3
Name           Garcia, Miss Rose
Sex                       female
Age                         44.0
SibSp                          0
Parch                          2
Ticket                   SM99694
Fare                        4.41
Cabin                        NaN
Embarked                       M
Name: 34, dtype: object

PassengerId                      36
Survived                          0
Pclass                            3
Name           Thompson, Mrs. Agnes
Sex                          female
Age                            24.1
SibSp                             0
Parch                             0
Ticket                      SM89478
Fare                           8.83
Cabin                           NaN
Embarked                          M
Name: 35, dtype: object

PassengerId                       37
Survived                           0
Pclass                             3
Name           Stewart, Mr. Lawrence
Sex                             male
Age                             14.1
SibSp                              0
Parch                              3
Ticket                       SM54433
Fare                            4.05
Cabin                            NaN
Embarked                           C
Name: 36, dtype: object

PassengerId                   38
Survived                       0
Pclass                         3
Name           Adams, Mr. Ernest
Sex                         male
Age                         35.1
SibSp                          1
Parch                          0
Ticket                   SM65058
Fare                        7.78
Cabin                        NaN
Embarked                       C
Name: 37, dtype: object

PassengerId                     39
Survived                         1
Pclass                           3
Name           Jones, Mr. Clarence
Sex                           male
Age                           25.7
SibSp                            2
Parch                            0
Ticket                     SM12688
Fare                         10.96
Cabin                          NaN
Embarked                         M
Name: 38, dtype: object

PassengerId                    40
Survived                        1
Pclass                          1
Name           Adams, Mr. Stanley
Sex                          male
Age                          57.5
SibSp                           0
Parch                           0
Ticket                    SM19744
Fare                         49.3
Cabin                         NaN
Embarked                        L
Name: 39, dtype: object

PassengerId                  41
Survived                      1
Pclass                        3
Name           King, Miss Elsie
Sex                      female
Age                        33.8
SibSp                         1
Parch                         1
Ticket                  SM71039
Fare                        3.5
Cabin                       NaN
Embarked                      C
Name: 40, dtype: object

PassengerId                     42
Survived                         1
Pclass                           2
Name           Williams, Mrs. Emma
Sex                         female
Age                           28.2
SibSp                            0
Parch                            1
Ticket                     SM21128
Fare                          4.92
Cabin                          NaN
Embarked                         C
Name: 41, dtype: object

PassengerId                    43
Survived                        1
Pclass                          2
Name           Roberts, Mr. David
Sex                          male
Age                          30.7
SibSp                           3
Parch                           0
Ticket                    SM28434
Fare                          3.5
Cabin                         NaN
Embarked                        L
Name: 42, dtype: object

PassengerId                        44
Survived                            0
Pclass                              2
Name           Mitchell, Mr. Clarence
Sex                              male
Age                               NaN
SibSp                               0
Parch                               1
Ticket                        SM55603
Fare                             9.12
Cabin                             NaN
Embarked                            L
Name: 43, dtype: object

PassengerId                    45
Survived                        1
Pclass                          3
Name           Johnson, Miss Emma
Sex                        female
Age                          14.5
SibSp                           0
Parch                           0
Ticket                    SM69616
Fare                          3.5
Cabin                         NaN
Embarked                        C
Name: 44, dtype: object

PassengerId                   46
Survived                       1

0      None
1      None
2      None
3      None
4      None
       ...
686    None
687    None
688    None
689    None
690    None
Length: 691, dtype: object

In [12]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C

In [18]:
def determine_independence(row):
    age=row.loc["Age"]
    p_class =row.loc["Pclass"]
    # print(age)
    # print(p_class)
    # print()
    if age <18 and p_class<3:
        return "Dependant"
    return "Self sponsored"

In [22]:
df.apply(determine_independence,axis=1)

0      Self sponsored
1      Self sponsored
2      Self sponsored
3      Self sponsored
4      Self sponsored
            ...
686    Self sponsored
687    Self sponsored
688    Self sponsored
689    Self sponsored
690    Self sponsored
Length: 691, dtype: object

In [23]:
df.apply(determine_independence,axis=1).value_counts()

Self sponsored    643
Dependant          48
Name: count, dtype: int64

In [24]:
df.apply(determine_independence,axis=1).value_counts(normalize=True)

Self sponsored    0.930535
Dependant         0.069465
Name: proportion, dtype: float64

In [25]:
df.apply(determine_independence,axis=1).value_counts(normalize=True)*100

Self sponsored    93.053546
Dependant          6.946454
Name: proportion, dtype: float64

## Scaling

In [ ]:
## standard scalar

In [26]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C

In [27]:
#standardizing age 
mean_age = df.Age.mean()
std_age = df.Age.std()
(df.Age-mean_age)/std_age

0     -0.608100
1      1.990682
2           NaN
3     -0.270047
4      1.448389
         ...
686    0.215904
687    0.215904
688    0.997652
689    0.821583
690    0.110263
Name: Age, Length: 691, dtype: float64

In [29]:
((df.Age-mean_age)/std_age).round(2)

0     -0.61
1      1.99
2       NaN
3     -0.27
4      1.45
       ...
686    0.22
687    0.22
688    1.00
689    0.82
690    0.11
Name: Age, Length: 691, dtype: float64

In [30]:
((df.Age-mean_age)/std_age).round(2).describe()

count    6.340000e+02
mean    -6.304106e-18
std      1.000160e+00
min     -2.190000e+00
25%     -7.275000e-01
50%      0.000000e+00
75%      6.500000e-01
max      2.990000e+00
Name: Age, dtype: float64

In [31]:
## Scale the fare column or normalizing the fare
(df.Fare-df.Fare.min())/(df.Fare.max()-df.Fare.min())

0      0.000000
1      0.004257
2      0.057000
3      0.115252
4      0.310393
         ...
686    0.487253
687    0.108590
688    0.225244
689    0.193789
690    0.008565
Name: Fare, Length: 691, dtype: float64

In [32]:
((df.Fare-df.Fare.min())/(df.Fare.max()-df.Fare.min())).describe()

count    691.000000
mean       0.158280
std        0.204835
min        0.000000
25%        0.019735
50%        0.057951
75%        0.255873
max        1.000000
Name: Fare, dtype: float64